/**
 * The data layer.
 *
 * Everything is a static JSON file fetched from ./data/. There is no API, no
 * backend, no database connection, and no request that leaves the machine
 * serving this site — except the one optional address lookup the user
 * explicitly triggers (see geocode.ts, which says so on screen before it runs).
 *
 * Fetches are memoised so a given file is pulled once per page load.
 */

import type {
  Award, BillClassification, DonorProfile, Industry, IndustryId, OverlapResult, VoteRecord,
} from '@ftm/core';

export interface BundleIndex {
  generatedAt: string;
  isSample: boolean;
  cycle: number;
  congress: number;
  counts: Record<string, number>;
  sources: {
    openfec: string; congress: string; classification: string;
    lastRun: { fec: string | null; congress: string | null; classify: string | null };
  };
  overlapFormula: string;
  /** Describes exactly what the contribution figures cover in THIS bundle. */
  moneyLabel?: string;
  disclaimers: { short: string; medium: string; long: string };
  coverageNotes: string[];
}

export interface MemberSummary {
  bioguideId: string;
  name: string;
  firstName?: string;
  lastName?: string;
  chamber: 'House' | 'Senate';
  state: string;
  district?: string;
  party?: string;
  imageUrl?: string;
  officialUrl?: string;
  fecCandidateIds: string[];
  sourceUrl: string;
  fetchedAt: string;
  committees: { committeeCode: string; committeeName: string; role?: string }[];
  donorSummary: {
    totalItemized: number;
    top: { industry: IndustryId; amount: number; share: number }[];
    unclassifiedShare: number;
  } | null;
}

export interface BillSummary {
  id: string;
  congress: number;
  billType: string;
  billNumber: string;
  title: string;
  introducedDate?: string;
  latestActionDate?: string;
  latestActionText?: string;
  policyArea?: string;
  subjects: string[];
  sponsorBioguideId?: string;
  cosponsorCount: number;
  committeeNames: string[];
  congressDotGovUrl: string;
  industries: { industry: IndustryId; confidence: number }[];
  classificationMethod: 'llm' | 'keyword-fallback' | null;
  topOverlap: { bioguideId: string; score: number } | null;
  overlapCount: number;
}

export interface MeaningFacts {
  percentile: number;
  median: number;
  n: number;
  ordinary: { kind: string; text: string }[];
  unattributedShare: number;
}

export interface BillDetail {
  bill: {
    id: string; congress: number; billType: string; billNumber: string; title: string;
    introducedDate?: string; latestActionDate?: string; latestActionText?: string;
    policyArea?: string; subjects: string[]; sponsorBioguideId?: string;
    cosponsorBioguideIds: string[]; committeeCodes: string[]; committeeNames: string[];
    officialSummary?: string; congressDotGovUrl: string; sourceUrl: string; fetchedAt: string;
  };
  classification: BillClassification | null;
  overlaps: (OverlapResult & {
    member: { name: string; chamber: string; state: string; district?: string; imageUrl?: string; role: string } | null;
    donorProfile: DonorProfile | null;
    meaning?: MeaningFacts | null;
  })[];
  votes: { id: string; date: string; question: string; result: string; sourceUrl: string; positions: number }[];
  disclaimer: string;
}

export interface MemberDetail {
  member: MemberSummary;
  donorProfile: DonorProfile | null;
  topDonors: { name: string; industry: IndustryId; amount: number; kind: string; sourceUrl: string }[];
  overlaps: (OverlapResult & { bill: BillSummary | null; meaning?: MeaningFacts | null })[];
  votes: { id: string; billId?: string; date: string; question: string; result: string; position: string; sourceUrl: string }[];
  districtAwards: Award[];
  disclaimer: string;
}

/**
 * A curated home-page row.
 *
 * Same shape as an `overlaps.json` row, plus `featureNote` — the export's own
 * one-line statement of the rule it used to pick this set. The home page renders
 * that note verbatim rather than paraphrasing it, so the selection rule shown to
 * the reader is the selection rule the pipeline actually applied.
 *
 * `featured.json` is generated by the export step. It is deliberately optional:
 * an older bundle will not have it, and the home page falls back to the raw
 * overlap list rather than showing an error (see pages/Home.tsx).
 */
export interface FeaturedOverlap extends OverlapResult {
  featureNote?: string;
}

export interface SearchEntry {
  t: 'member' | 'bill' | 'industry' | 'recipient';
  id: string;
  label: string;
  sub: string;
  terms: string;
}

const BASE = `${import.meta.env.BASE_URL ?? './'}data/`.replace(/\/{2,}/g, '/');

const cache = new Map<string, Promise<unknown>>();

export class DataMissingError extends Error {
  constructor(public readonly file: string) {
    super(
      `Could not load ${file}. The data bundle has not been generated yet.\n\n` +
        `Run this once, from the repository root:\n\n    npm run pipeline\n\n` +
        `It needs no API keys for a first run.`,
    );
    this.name = 'DataMissingError';
  }
}

export function loadJson<T>(file: string): Promise<T> {
  const existing = cache.get(file);
  if (existing) return existing as Promise<T>;
  const p = fetch(`${BASE}${file}`)
    .then((r) => {
      if (!r.ok) throw new DataMissingError(file);
      return r.json() as Promise<T>;
    })
    .catch((err) => {
      cache.delete(file);
      if (err instanceof DataMissingError) throw err;
      throw new DataMissingError(file);
    });
  cache.set(file, p);
  return p;
}

export const getIndex = () => loadJson<BundleIndex>('index.json');
export const getIndustries = () => loadJson<Industry[]>('industries.json');
export const getLegislators = () => loadJson<MemberSummary[]>('legislators.json');
export const getBills = () => loadJson<BillSummary[]>('bills.json');
export const getAwards = () => loadJson<Award[]>('awards.json');
export const getSearchIndex = () => loadJson<SearchEntry[]>('search.json');
export const getOverlaps = () => loadJson<OverlapResult[]>('overlaps.json');

/**
 * The curated featured set, or `null` when the bundle predates it.
 *
 * Absence is a normal state, not an error: `loadJson` throws DataMissingError on
 * a 404, and a missing *optional* file must not take the home page down with it.
 * Callers get `null` and choose their own fallback.
 */
export const getFeatured = (): Promise<FeaturedOverlap[] | null> =>
  loadJson<FeaturedOverlap[]>('featured.json')
    .then((rows) => (Array.isArray(rows) ? rows : null))
    .catch(() => null);

/** What the home page needs: the rows, the rule that picked them, and whether one was applied. */
export interface FeaturedSet {
  rows: FeaturedOverlap[];
  /** The export's own statement of the selection rule, or null if there was none. */
  note: string | null;
  /** False when this is the raw top-of-`overlaps.json` fallback, which has no rule. */
  curated: boolean;
}

/**
 * The featured set, with the fallback done here rather than in the view.
 *
 * The fallback fetch is lazy on purpose: `featured.json` is 10 KB and
 * `overlaps.json` is 2.2 MB, so a bundle that has the curated file must not pay
 * for the one it does not need. The home page used to pull the whole overlap
 * list on every visit; now it only does so on an older bundle that has nothing
 * else to show.
 */
export async function getFeaturedSet(): Promise<FeaturedSet> {
  const curated = await getFeatured();
  if (curated && curated.length > 0) {
    return {
      rows: curated,
      note: curated.find((o) => o.featureNote)?.featureNote ?? null,
      curated: true,
    };
  }
  return { rows: await getOverlaps(), note: null, curated: false };
}
export const getBillDetail = (id: string) => loadJson<BillDetail>(`bill/${id}.json`);
export const getMemberDetail = (id: string) => loadJson<MemberDetail>(`member/${id}.json`);

export type { Award, DonorProfile, Industry, IndustryId, OverlapResult, VoteRecord };
